apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: jcalderonmunir/ban-client-service:placeholder
          imagePullPolice: Always
          env:
            - name: DB_URL
              value: jdbc:postgresql://192.168.20.22:5432/client_db
            - name: DB_USERNAME
              value: usuario
            - name: DB_PASSWORD
              value: contrasena_segura
          ports:
            - containerPort: 8080
